### PR TITLE
Release 1.2.6

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@pelson should I add npm as a build dependency in the conda recipe?

**Comment by pelson** [comment]
Sure. FWIW it is packaged under nodejs: https://anaconda.org/conda-forge/nodejs

**Comment by SylvainCorlay** [comment]
Hum it goes a bit father but the npm build fails. Works on mutliple platforms for me. I guess I should get into ninja mode and try with your docker image.

**Comment by SylvainCorlay** [comment]
Travis-ci is passing but not circleci and appveyor.

**Pull request merged**
