### PR TITLE
update to 3.1.0

### PR DESCRIPTION
**Pull request by jasongrout**

### CODE REVIEW

**Comment by jasongrout** [comment]
Appveyer unpredictably ends with:

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
The batch file cannot be found.
Command exited with code 1
```

**Comment by jasongrout** [comment]
See https://github.com/conda/conda/issues/6527

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks @jasongrout.

**Pull request merged**
