### PR TITLE
Update to 1.2.1

### PR DESCRIPTION
**Pull request by ocefpaf**
@SylvainCorlay, @parente, and @willingc would you be willing to be added as maintainers of this recipe? If so I can do that in this PR for you.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
No problem thanks!

**Comment by ocefpaf** [comment]
> No problem thanks!

Just did. Thanks! You should get commit right once the PR is merged.

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Comment by jakirkham** [comment]
@SylvainCorlay, as this is your first time being added as a maintainer here, I'm going to explain our Rube Goldberg machine of CIs and what it will do next. Once your name is added to this recipe, another batch script will run on a CI and pick up your handle from this list in this feedstock. It will then add you as a maintainer. This will cause GitHub to send you an email inviting you to join conda-forge. Once accepted this will add you to the `widgetsnbextension` team, which has commit privileges on this repo. Going forward, anywhere you add your GitHub handle or it is added (with your permission) will automatically lead to you getting commit privileges on those repos. There will be no other action required on your behalf.

Thanks for helping us maintain `widgetsnbextension` and welcome to conda-forge. 😄

**Comment by willingc** [comment]
Sure!

**Comment by jakirkham** [comment]
I merged this one already, but we can add you in another PR, @willingc.

**Comment by willingc** [comment]
Sounds good @jakirkham. Thanks.

**Comment by jakirkham** [comment]
> Sounds good @jakirkham. Thanks.

Cool, adding you in this PR ( https://github.com/conda-forge/widgetsnbextension-feedstock/pull/3 ).

**Pull request merged**
