### PR TITLE
Adding post [un]link files

### LINKED ISSUE #4: [question] nbextension enable in post-link script?
Are we going to make people run the `jupyter nbextension enable --py widgetnbextension`, or do that in a post-install script?

We have been packaging our [stuff](https://github.com/Anaconda-Platform/nbpresent/blob/master/conda.recipe/post-link.sh) with this enabled:

```bash
# post-link.sh
"${PREFIX}/bin/jupyter-nbextension" enable nbpresent --py --sys-prefix
"${PREFIX}/bin/jupyter-serverextension" enable nbpresent --py --sys-prefix
```

This is still not ideal, as it makes it harder to put extensions in things like the Anaconda Distribution or other [Contructor](https://github.com/conda/constructor) products, but I feel it's a lot more reasonable for the user. For example, this handles the "multiple versions installed in different envs" case, etc.

Perhaps once we get `nbconfig.d` this can be entirely handled by just running the API commands in `build`, with the correct files ending up in `etc/jupyter`

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Closes #4, method used by @bollwyvl in nbpresent.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @SylvainCorlay!

**Comment by jakirkham** [comment]
Should we be bumping the build number to ensure these are included in the package?

**Comment by SylvainCorlay** [comment]
You tell me! I have no experience with conda-forge.

**Comment by jakirkham** [comment]
Sorry. That should be a statement.

The issue is we never overwrite packages in the `conda-forge` channel. So, if we want new functionality in the recipe, we need to bump the build number to get a new release.

I have gone ahead and done this here ( https://github.com/conda-forge/widgetsnbextension-feedstock/pull/7 ).

Thanks for your contribution @SylvainCorlay.

**Comment by bollwyvl** [comment]
@SylvainCorlay Awesome! Our scheme for making conda the most reasonable way to install good Jupyter stuff continues!

**Pull request merged**
