### PR TITLE
Release version 3.2.0

### PR DESCRIPTION
**Pull request by pbugnion**

### CODE REVIEW

**Comment by jasongrout** [comment]
Can we just double-check to see if having an enabled extension not installed gives errors? Either on startup, or on `nbextension list`?

Also, can you add yourself to the maintainers at https://github.com/conda-forge/widgetsnbextension-feedstock/blob/master/recipe/meta.yaml#L35 ?

**Comment by pbugnion** [comment]
Apologies for the delay. I ended up getting stuck on a very delayed flight.

Uninstalling an extension without disabling it works fine, with the following caveats (I explicitly uninstalled jupyter-gmaps with pip without running `jupyter nbextension disable`):

- it does leave a somewhat ugly validation error in `jupyter nbextension list` (validated on notebook 5.4.1): 

screen shot 2018-03-31 at 18 48 42

- it causes an ugly traceback in the browser console:

screen shot 2018-03-31 at 18 55 23

As far as I can tell, the frontend doesn't even try to load the extension at start-up.

As it stands, I'm tempted to revert commit c43f604, ie carry on explicitly disabling the extension. FAICT, the only users somewhat negatively affected by this are people who install and uninstall ipywidgets with conda, then try and install it with pip without explicitly enabling it. In the [installation guide](https://ipywidgets.readthedocs.io/en/latest/user_install.html), we still explicitly tell users to run `jupyter nbextension enable`, regardless of notebook version.

Happy to revert c43f604 if there's enough consensus that that's the right approach.

**Comment by jakirkham** [comment]
+1 for keeping the unlink script.

The issue that users have encountered with unlinking is a `conda` issue which should be resolved in 4.4+.

**Comment by maartenbreddels** [comment]
The 'problem' is, if we don't get rid of the unlink script, we can never get rid of the link and unlink scripts. We can live with it for a short while, but I'd like to get rid of it eventually.
Any objection to running this monster in post-unlink?
`python -c "import os; import notebook.nbextensions as nbe; import notebook.config_manager as cm; config = cm.BaseJSONConfigManager(config_dir=os.path.join(nbe._get_config_dir(sys_prefix=True), 'nbconfig'), read_directory=False); state = config.get('notebook'); state.get('load_extensions', {}).pop('jupyter-js-widgets/extension', None); config.set('notebook', state)"`

**Comment by jasongrout** [comment]
Huh, I wonder if that is the equivalent of `nbextension uninstall`- I would hope an uninstall step does not need a disable step (thought that would break parity).

**Comment by jasongrout** [comment]
Not sure, but is that what these lines do? https://github.com/jupyter/notebook/blob/faa0cab302bb86f0329a512a4ece1f772b29b4c7/notebook/nbextensions.py#L273-L279

**Comment by SylvainCorlay** [comment]
In addition to the disable there is a need for a 'remove' command that
would remove the entry for an extension instead of setting it to false or
true.

**Comment by pbugnion** [comment]
I just tried it now, and I think Jason is right -- `jupyter nbextension uninstall` removes the entry from `notebook.json` (as well as removing the actual extension source).

It seems like it therefore makes sense for the pre-unlink to be `jupyter nbextension uninstall widgetsnbextension`?

**Comment by jasongrout** [comment]
@pbugnion - if that's what it does, then it's weird that there is asymmetry between installing/enabling, but just needing to uninstall, but not disable. Perhaps that's an argument for `nbextension install` automatically doing an `enable` (which may be moot now that we have the conf.d approach).

**Comment by maartenbreddels** [comment]
> assuming pre-unlink is run before the Python source is removed\

If that is true, it will be much simpler.

The confusing part of that piece of code, is that by setting it to None, [it will get removed](https://github.com/jupyter/notebook/blob/master/notebook/config_manager.py#L28)

**Comment by pbugnion** [comment]
I've now validated that running 

```
jupyter nbextension uninstall --py --sys-prefix widgetsnbextension
```

removes the entry from `notebook.json` on both notebook 4.4.1 and 5.4.1 (we claim to support everything between those). In particular, on 5.4.1, running 

```
jupyter nbextension uninstall --py --sys-prefix widgetsnbextension
pip uninstall widgetsnbextension
pip install widgetsnbextension
```

leaves you with an installation of ipywidgets enabled by default, which is what we need to be able to eventually remove the enable step.

I've pushed updated pre-unlink scripts that uninstall the nbextension.

**Comment by SylvainCorlay** [comment]
Awesome! Merging.

**Comment by pbugnion** [comment]
Awesome, thanks for everyone's help!

**Comment by jasongrout** [comment]
I suppose all of the other widgets packages should be updated with this uninstall trick.

**Comment by pbugnion** [comment]
> I suppose all of the other widgets packages should be updated with this uninstall trick.

You mean community widgets like ipyvolume, bqplot etc.?

**Comment by maartenbreddels** [comment]
Awesome indeed, yes, this should go to all other packages that use
'disable' if we wanna make users happy. I'll take care of ipyvolume.

(from mobile phone)

**Pull request merged**
