### PR TITLE
Sync with AnacondaRecipes

### PR DESCRIPTION
**Pull request by jjhelmus**
Sync recipe with the version from the AnacondaRecipes repository.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Looks good to me!

**Comment by jasongrout** [comment]
The build should be bumped, right?

**Comment by SylvainCorlay** [comment]
I don't think that the build result is modified so I guess that it is fine.

**Comment by jjhelmus** [comment]
The contents of the package should be the same so no build number change is need, although I'm happy to bump it anyway.

**Pull request merged**
