### PR TITLE
Make the package a noarch package

### PR DESCRIPTION
**Pull request by jasongrout**
See https://github.com/conda-forge/conda-smithy/pull/531

### CODE REVIEW

**Comment by jasongrout** [comment]
@ocefpaf - we've had user file some errors that seem to indicate that some files we are trying to copy at https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/setup.py#L178 aren't copied, and the only relevant change seems to be this noarch PR. I'll be able to narrow this down more in a few days, but do you know of any reason off the top of your head that a noarch package wouldn't copy files?

See https://github.com/jupyter-widgets/ipywidgets/issues/1721 and https://github.com/jupyter-widgets/ipywidgets/issues/1720. Users report that our pip package correctly copy the files, but the conda-forge one doesn't seem to do so.

**Comment by ocefpaf** [comment]
Ping @msarahan.

Until we figure this out 23 can revert to an arch aware pkg.

**Comment by jakirkham** [comment]
Just pulled the `noarch: python` package so users should be able to install a working version again. Agreed that we should revert `noarch: python` for this feedstock lest another broken release gets added.

**Comment by jasongrout** [comment]
Thanks!

**Comment by jakirkham** [comment]
Also performed the reversion in PR ( https://github.com/conda-forge/widgetsnbextension-feedstock/pull/30 ).

**Pull request merged**
