### PR TITLE
Release widgetsnbextension 1.2.3

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by minrk** [comment]
Looks like the file hasn't made it to pypi.io, so download is failing. Can rebuild when:

    wget https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-1.2.3.tar.gz

succeeds. The file is there in UI, 1.2.2 URL downloads. Not sure what the process for updating pypi.io redirect URLs is.

**Comment by SylvainCorlay** [comment]
Yeah I don't know why pypi releases are not available on pypi.io right away. It has been almost 12 hours...

**Comment by SylvainCorlay** [comment]
This is ready. Required for the ipywidgets one.

**Comment by jakirkham** [comment]
Please reset the build number when bumping the version number.

**Comment by SylvainCorlay** [comment]
Done.

**Pull request merged**
